# SwiftLint Configuration
# Follow Swift best practices and conventions

# Paths to include during linting
included:
  - sorted

# Paths to exclude during linting
excluded:
  - Pods
  - Carthage
  - .build
  - build
  - DerivedData
  - sortedTests
  - sortedUITests
  - sorted.xcodeproj

# Disable specific rules
disabled_rules:
  - trailing_comma # Allow trailing commas in arrays/dictionaries

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count # Prefer isEmpty over count == 0
  - empty_string # Prefer isEmpty over comparing to ""
  - explicit_init # Discourage explicit calls to init
  - first_where # Prefer .first(where:) over .filter { }.first
  - force_unwrapping # Warn on force unwrapping
  - implicitly_unwrapped_optional # Warn on implicitly unwrapped optionals
  - sorted_imports # Keep imports sorted
  - vertical_whitespace_closing_braces # Enforce vertical whitespace before closing braces
  - vertical_whitespace_opening_braces # Enforce vertical whitespace after opening braces
  - closure_spacing # Enforce spacing in closures
  - redundant_nil_coalescing # Warn on redundant nil coalescing
  - multiline_parameters # Enforce multiline parameters
  - multiline_arguments # Enforce multiline arguments

# Analyzer rules (only run by 'swiftlint analyze')
analyzer_rules:
  - unused_import # Warn on unused imports

# Rules with custom configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
    - to
    - db
    - at
    - in
    - on
    - up
    - ok

nesting:
  type_level:
    warning: 2

force_cast: warning
force_try: warning
force_unwrapping: warning

# Custom rules for project-specific conventions
custom_rules:
  # Encourage proper copyright headers
  no_copyright:
    name: "Copyright Header"
    regex: '(Copyright|©).*'
    match_kinds:
      - comment
    severity: warning

  # Encourage proper MARK usage
  marks_empty_space:
    name: "Marks Empty Space"
    regex: '// MARK: ?$'
    message: "MARK comments should not be empty"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
